### PR TITLE
Make regular fields suitable for deserialization

### PR DESCRIPTION
**Pull request by Jamim**
These changes also:
 - Add the ability to use classes at `deserialization_schema_selector`
 - Update `setup.cfg` and `.travis.yml`

### CODE REVIEW

**Comment by Bachmann1234** [comment]
Very nice! Thanks again!

**Comment by Bachmann1234** [comment]
Woah, aint it 3am in your part of the world @Jamim ?

**Comment by Bachmann1234** [comment]
https://pypi.org/project/marshmallow-polyfield/5.2/ Tagged and released.

**Comment by Jamim** [comment]
> Woah, aint it 3am in your part of the world @Jamim ?

Yep, but tomorrow (actually, today for me) is Sunday :smile:

**Pull request merged**
